routes/web.php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(
    ['register'=>false]
);

Route::get('/',[\App\Http\Controllers\HomeController::class,'welcome'])->middleware('Localization');
Route::get('/post/{id}',[\App\Http\Controllers\HomeController::class,'viewPost'])->name('home.single.post');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');








Route::group(['middleware'=>['auth:web','Localization'],'prefix'=>'admin','as'=>'admin.'],function(){

Route::get('/', [App\Http\Controllers\AdminController::class, 'index'])->name('dashboard');
Route::post('/update-fcm-token', [App\Http\Controllers\AdminController::class, 'updateFcmToken'])->name('update.fcm.token');
Route::get('/locale/{lang}',[App\Http\Controllers\AdminController::class, 'changeLocale'])->name('change.locale');

        Route::group(["prefix"=>'users','as'=>'users.'],function(){
              Route::get('/', [App\Http\Controllers\Admin\UserConteoller::class, 'index'])->name('index');
              Route::get('/create', [App\Http\Controllers\Admin\UserConteoller::class, 'create'])->name('create');
              Route::post('/store', [App\Http\Controllers\Admin\UserConteoller::class, 'store'])->name('store');
              Route::get('/edit/{admin}', [App\Http\Controllers\Admin\UserConteoller::class, 'edit'])->name('edit');
              Route::post('/update/{admin}', [App\Http\Controllers\Admin\UserConteoller::class, 'update'])->name('update');
              Route::post('/destroy/{admin}', [App\Http\Controllers\Admin\UserConteoller::class, 'destroy'])->name('destroy');
        });

    Route::resource('category', \App\Http\Controllers\CategoryController::class);
    Route::resource('post', \App\Http\Controllers\PostController::class);
    Route::group(['prefix'=>'notifications'], function (){
        Route::get('/',[\App\Http\Controllers\Admin\NotificationController::class,'index'])->name('notification.form');
        Route::post('/send',[\App\Http\Controllers\Admin\NotificationController::class,'sendNotification'])->name('notification.send');
    });



});


//Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable=['title','description','category_id','image'];
    protected $appends=['main_image_url'];

    public function category(){
        return $this->belongsTo(Category::class,'category_id')->withDefault(['name'=>'غير مصنف']);
    }
    public function getMainImageUrlAttribute(){
        if($this->image){

        return  asset('uploads/'.$this->image);
        }
        return null;
    }

    public function scopeSearch($q,$request){
        if($request->has('title') && $request->title){
            $q->where('title','like','%'.$request->title.'%');
        }
        if($request->has('category_id')&& $request->category_id){
            $q->where('category_id',$request->category_id);
        }
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $posts = Post::search($request)->orderBy('created_at','desc')->get();
        $data['posts']=$posts;
        $data['categories']=Category::get();
        return view('admin.post.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $data['categories']=Category::get();
        return view('admin.post.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            ['title'=>'required',
            "description"=>"required",
            "category_id"=>"required",
            "image"=>"required|image|mimes:jpeg,jpg,png,svg,gif",

            ]
        );
//        $data= $request->all()->except('_token');
//        $data->merge(['password'=>Hash::make('242134')]);

        $fileName='';
        if($request->hasFile('image')){
            $fileName=time().rand(1,10000).'.'.$request->file('image')->getClientOriginalExtension();
            $request->image->move(public_path('uploads'),$fileName);
        }
        $post=Post::create([
            'title'=>$request->title,
            'description'=>$request->description,
            'category_id'=>$request->category_id,
            'image'=>$fileName
        ]);

        return redirect(route('admin.post.index'))->with(['success'=>'تم اضافة الخبر بنجاح']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/post/create.blade.php
@extends('admin.layouts.app')
@section('content')

    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Create new post
            </h3>
            <div class="card-toolbar">

            </div>
        </div>
        <!--begin::Form-->

        <div class="card-body">

            {{--                                @if($errors->any())--}}
            {{--                                    <label class="alert alert-danger">--}}
            {{--                                        <ul class="list">--}}


            {{--                                        @foreach($errors->all() as $error)--}}

            {{--                                            <li> {{$error}}</li>--}}
            {{--                                       @endforeach--}}
            {{--                                        </ul>--}}
            {{--                                    </label>--}}
            {{--                                @endif--}}

            <form method="POST" action="{{ route('admin.post.store') }}" enctype="multipart/form-data">
                @csrf

                <div class="form-group row">
                    <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('title') }}</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="name" autofocus>

                        @error('title')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Description') }}</label>

                    <div class="col-md-6">
                        <textarea id="description" type="text" class="form-control summernote  @error('description') is-invalid @enderror" name="description" required autocomplete="name" autofocus rows="10">{{old('description')}}</textarea>

                        @error('description')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>


                <div class="form-group row">
                    <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Category') }}</label>

                    <div class="col-md-6">

                        <select name="category_id" class="form-control">
                            <option value="" selected>اختر تصنيف الخبر</option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}"  {{old('category_id') ==$category->id ?'selected':''}}>
                                    {{$category->name}}
                                </option>
                            @endforeach

                        </select>
                        @error('category_id')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>


                <div class="form-group row">
                    <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Article image') }}</label>

                    <div class="col-md-6">
                       <input type="file" accept="image/*" name="image"/>
                        @error('image')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>


                <div class="card-footer">
                    <button type="submit" class="btn btn-primary mr-2">
                        Save
                    </button>
                    {{--                                <button type="reset" class="btn btn-secondary">Cancel</button>--}}
                </div>
            </form>
            <!--end::Form-->
        </div>
@endsection
@push('js')
    <script>
        $(document).ready(function(){
            $('.summernote').summernote({
                height:400
            });
        });
    </script>
@endpush

resources/views/admin/post/index.blade.php
@extends('admin.layouts.app')
@section('content')

    <div class="card card-custom gutter-b">
        <div class="card-header">
            <div class="card-title">
                <h3 class="card-label"> Posts Lists</h3>
            </div>

            <div class="card-toolbar">
                <div class="example-tools justify-content-center">
                    <a class="btn btn-primary" href="{{route('admin.post.create')}}" >
                        Create new post
                    </a>
                    {{--                    <span class="example-toggle" data-toggle="tooltip" title="" data-original-title="View code"></span>--}}
                    {{--                    <span class="example-copy" data-toggle="tooltip" title="" data-original-title="Copy code"></span>--}}
                </div>
            </div>

        </div>
        <div class="card-body">

            @if(session()->has('success'))
                <div class="row">


                    <label class="alert alert-success">
                        {{session()->get('success')}}
                    </label>
                </div>
            @endif

            {{app()->getLocale()}}
            <div class="row">
                <form action="{{route('admin.post.index')}}">
                    <div class="row">
                        <div class="form-group">
                            <input type="text" name="title" class="form-control" value="{{request('title')}}"/>

                        </div>

                        <div class="form-group">
                            <select name="category_id" class="form-control">
                                <option value=""> Choose category</option>
                                @foreach($categories as $category)
                                <option value="{{$category->id}}" {{ request('category_id')==$category->id?'selected':'' }}>
                                    {{$category->name}}
                                </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-secondary">
                                Filter
                            </button>
                            <a href="{{route('admin.post.index')}}"  class="btn btn-bg-light">
                                Clear
                            </a>
                        </div>
                    </div>
                </form>
            </div>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th colspan="2">{{__('admin.posts.title')}}</th>
                    <th >{{__('admin.posts.category')}}</th>
                    <th >{{__('admin.posts.created_at')}}</th>

                </tr>
                </thead>
                <tbody>
                @php
                 \Carbon\Carbon::setLocale('ar');
                 @endphp
                @foreach($posts as $key=>$post)
                    <tr>
                        <td> {{ $loop->iteration }}</td>
                        <td>
                            <a href="{{$post->main_image_url}}" target="_blank">
                                <img src="{{$post->main_image_url}}" alt="لا يوجد صورة" width="50"/>
                            </a>

                        </td>
                        <td> {{$post->title}}</td>

                        <td> {{$post->category->name}}</td>
                        <td>{{
    \Carbon\Carbon::parse($post->created_at)->diffForHumans(now())

}}</td>

                    </tr>
                @endforeach
                </tbody>
            </table>




        </div>
    </div>
@endsection