routes/web.php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(
    ['register'=>false]
);

Route::get('/',[\App\Http\Controllers\HomeController::class,'welcome'])->middleware('Localization');
Route::get('/post/{id}',[\App\Http\Controllers\HomeController::class,'viewPost'])->name('home.single.post');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');








Route::group(['middleware'=>['auth:web','Localization'],'prefix'=>'admin','as'=>'admin.'],function(){

Route::get('/', [App\Http\Controllers\AdminController::class, 'index'])->name('dashboard');
Route::post('/update-fcm-token', [App\Http\Controllers\AdminController::class, 'updateFcmToken'])->name('update.fcm.token');
Route::get('/locale/{lang}',[App\Http\Controllers\AdminController::class, 'changeLocale'])->name('change.locale');

        Route::group(["prefix"=>'users','as'=>'users.'],function(){
              Route::get('/', [App\Http\Controllers\Admin\UserConteoller::class, 'index'])->name('index');
              Route::get('/create', [App\Http\Controllers\Admin\UserConteoller::class, 'create'])->name('create');
              Route::post('/store', [App\Http\Controllers\Admin\UserConteoller::class, 'store'])->name('store');
              Route::get('/edit/{admin}', [App\Http\Controllers\Admin\UserConteoller::class, 'edit'])->name('edit');
              Route::post('/update/{admin}', [App\Http\Controllers\Admin\UserConteoller::class, 'update'])->name('update');
              Route::post('/destroy/{admin}', [App\Http\Controllers\Admin\UserConteoller::class, 'destroy'])->name('destroy');
        });

    Route::resource('category', \App\Http\Controllers\CategoryController::class);
    Route::resource('post', \App\Http\Controllers\PostController::class);
    Route::group(['prefix'=>'notifications'], function (){
        Route::get('/',[\App\Http\Controllers\Admin\NotificationController::class,'index'])->name('notification.form');
        Route::post('/send',[\App\Http\Controllers\Admin\NotificationController::class,'sendNotification'])->name('notification.send');
    });



});


//Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Admin/NotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Notifications\NormalNotification;
use App\Traits\ApiResponse;
use Illuminate\Http\Request;

class NotificationController extends Controller
{
    use ApiResponse;
    public  function  index(){
        $data['users']=User::whereNotNull('fcm_token')->get();
        return view('admin.notification.index',$data);
    }

    public function sendNotification(Request $request){

        $request->validate([
            'title'=>'required',
            'message'=>'required',
            'user_id'=>'required'
        ]);
        $user = User::find($request->user_id);

        if($user && $user->fcm_token){
            $message=[
                'title'=>$request->title,
                "message"=>$request->message,
                'web_link'=>route('admin.users.index')
            ];
            $this->sendFCM($user->fcm_token,$message);
            $user->notify(new NormalNotification($message));
        }

        return redirect()->back()->with(['success','تم ارسال الاشعار بنجاح']);
    }
}

resources/views/admin/notification/index.blade.php
@extends('admin.layouts.app')
@section('content')

    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Create new Notification
            </h3>
            <div class="card-toolbar">

            </div>
        </div>
        <!--begin::Form-->

        <div class="card-body">

            {{--                                @if($errors->any())--}}
            {{--                                    <label class="alert alert-danger">--}}
            {{--                                        <ul class="list">--}}


            {{--                                        @foreach($errors->all() as $error)--}}

            {{--                                            <li> {{$error}}</li>--}}
            {{--                                       @endforeach--}}
            {{--                                        </ul>--}}
            {{--                                    </label>--}}
            {{--                                @endif--}}

            <form method="POST" action="{{ route('admin.notification.send') }}">
                @csrf

                <div class="form-group row">
                    <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('title') }}</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="name" autofocus>

                        @error('title')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Message') }}</label>

                    <div class="col-md-6">
                        <textarea id="description" type="text" class="form-control summernote  @error('Message') is-invalid @enderror" name="message" required autocomplete="name" autofocus rows="10">{{old('description')}}</textarea>

                        @error('Message')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>


                <div class="form-group row">
                    <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('User') }}</label>

                    <div class="col-md-6">

                        <select name="user_id" class="form-control">
                            <option value="" selected>المستخدم  </option>
                            @foreach($users as $user)
                                <option value="{{$user->id}}"  {{old('user_id') ==$user->id ?'selected':''}}>
                                    {{$user->name}}
                                </option>
                            @endforeach

                        </select>
                        @error('user_id')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>




                <div class="card-footer">
                    <button type="submit" class="btn btn-primary mr-2">
                        Send notification
                    </button>
                    {{--                                <button type="reset" class="btn btn-secondary">Cancel</button>--}}
                </div>
            </form>
            <!--end::Form-->
        </div>
        @endsection