routes/web.php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(
    ['register'=>false]
);

Route::get('/',[\App\Http\Controllers\HomeController::class,'welcome'])->middleware('Localization');
Route::get('/post/{id}',[\App\Http\Controllers\HomeController::class,'viewPost'])->name('home.single.post');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');








Route::group(['middleware'=>['auth:web','Localization'],'prefix'=>'admin','as'=>'admin.'],function(){

Route::get('/', [App\Http\Controllers\AdminController::class, 'index'])->name('dashboard');
Route::post('/update-fcm-token', [App\Http\Controllers\AdminController::class, 'updateFcmToken'])->name('update.fcm.token');
Route::get('/locale/{lang}',[App\Http\Controllers\AdminController::class, 'changeLocale'])->name('change.locale');

        Route::group(["prefix"=>'users','as'=>'users.'],function(){
              Route::get('/', [App\Http\Controllers\Admin\UserConteoller::class, 'index'])->name('index');
              Route::get('/create', [App\Http\Controllers\Admin\UserConteoller::class, 'create'])->name('create');
              Route::post('/store', [App\Http\Controllers\Admin\UserConteoller::class, 'store'])->name('store');
              Route::get('/edit/{admin}', [App\Http\Controllers\Admin\UserConteoller::class, 'edit'])->name('edit');
              Route::post('/update/{admin}', [App\Http\Controllers\Admin\UserConteoller::class, 'update'])->name('update');
              Route::post('/destroy/{admin}', [App\Http\Controllers\Admin\UserConteoller::class, 'destroy'])->name('destroy');
        });

    Route::resource('category', \App\Http\Controllers\CategoryController::class);
    Route::resource('post', \App\Http\Controllers\PostController::class);
    Route::group(['prefix'=>'notifications'], function (){
        Route::get('/',[\App\Http\Controllers\Admin\NotificationController::class,'index'])->name('notification.form');
        Route::post('/send',[\App\Http\Controllers\Admin\NotificationController::class,'sendNotification'])->name('notification.send');
    });



});


//Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')
@section('content')


                    <div class="card card-custom">
                        <div class="card-header">
                            <h3 class="card-title">
                              Create new Admin
                            </h3>
                            <div class="card-toolbar">

                            </div>
                        </div>
                        <!--begin::Form-->

                            <div class="card-body">

{{--                                @if($errors->any())--}}
{{--                                    <label class="alert alert-danger">--}}
{{--                                        <ul class="list">--}}


{{--                                        @foreach($errors->all() as $error)--}}

{{--                                            <li> {{$error}}</li>--}}
{{--                                       @endforeach--}}
{{--                                        </ul>--}}
{{--                                    </label>--}}
{{--                                @endif--}}

                                <form method="POST" action="{{ route('admin.users.store') }}">
                                    @csrf

                                    <div class="form-group row">
                                        <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Name') }}</label>

                                        <div class="col-md-6">
                                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="email" class="col-md-2 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                        <div class="col-md-6">
                                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                            @error('email')
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="password" class="col-md-2 col-form-label text-md-right">{{ __('Password') }}</label>

                                        <div class="col-md-6">
                                            <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                            @error('password')
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="password-confirm" class="col-md-2 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                        <div class="col-md-6">
                                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                                        </div>
                                    </div>

{{--                                <div class="form-group mb-8">--}}
{{--                                    <div class="alert alert-custom alert-default" role="alert">--}}
{{--                                        <div class="alert-icon"><i class="flaticon-warning text-primary"></i></div>--}}
{{--                                        <div class="alert-text">--}}
{{--                                            The example form below demonstrates common HTML form elements that receive updated styles from Bootstrap with additional classes.--}}
{{--                                        </div>--}}
{{--                                    </div>--}}
{{--                                </div>--}}


                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary mr-2">
                                    {{ __('Add new Admin') }}
                                </button>
{{--                                <button type="reset" class="btn btn-secondary">Cancel</button>--}}
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>




@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')
@section('content')


    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                update admin information
            </h3>
            <div class="card-toolbar">

            </div>
        </div>
        <!--begin::Form-->

        <div class="card-body">



            {{--                                @if($errors->any())--}}
            {{--                                    <label class="alert alert-danger">--}}
            {{--                                        <ul class="list">--}}


            {{--                                        @foreach($errors->all() as $error)--}}

            {{--                                            <li> {{$error}}</li>--}}
            {{--                                       @endforeach--}}
            {{--                                        </ul>--}}
            {{--                                    </label>--}}
            {{--                                @endif--}}

            <form method="POST" action="{{ route('admin.users.update',$admin->id) }}">
                @csrf

                <div class="form-group row">
                    <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Name') }}</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                               name="name"  required autocomplete="name" autofocus
                        value="{{$admin->name}}">

                        @error('name')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="email" class="col-md-2 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                               name="email"  required autocomplete="email"
                               value="{{$admin->email}}">

                        @error('email')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>

{{--                <div class="form-group row">--}}
{{--                    <label for="password" class="col-md-2 col-form-label text-md-right">{{ __('Password') }}</label>--}}

{{--                    <div class="col-md-6">--}}
{{--                        <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">--}}

{{--                        @error('password')--}}
{{--                        <span class="invalid-feedback" role="alert">--}}
{{--                                        <strong>{{ $message }}</strong>--}}
{{--                                    </span>--}}
{{--                        @enderror--}}
{{--                    </div>--}}
{{--                </div>--}}

{{--                <div class="form-group row">--}}
{{--                    <label for="password-confirm" class="col-md-2 col-form-label text-md-right">{{ __('Confirm Password') }}</label>--}}

{{--                    <div class="col-md-6">--}}
{{--                        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">--}}
{{--                    </div>--}}
{{--                </div>--}}

                {{--                                <div class="form-group mb-8">--}}
                {{--                                    <div class="alert alert-custom alert-default" role="alert">--}}
                {{--                                        <div class="alert-icon"><i class="flaticon-warning text-primary"></i></div>--}}
                {{--                                        <div class="alert-text">--}}
                {{--                                            The example form below demonstrates common HTML form elements that receive updated styles from Bootstrap with additional classes.--}}
                {{--                                        </div>--}}
                {{--                                    </div>--}}
                {{--                                </div>--}}


                <div class="card-footer">
                    <button type="submit" class="btn btn-primary mr-2">
                        {{ __('Update admin information') }}
                    </button>
                    {{--                                <button type="reset" class="btn btn-secondary">Cancel</button>--}}
                </div>
            </form>
            <!--end::Form-->
        </div>




@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')
@section('content')

    <div class="card card-custom gutter-b">
        <div class="card-header">
            <div class="card-title">
                <h3 class="card-label"> Admins Lists</h3>
            </div>

            <div class="card-toolbar">
                <div class="example-tools justify-content-center">
                    <a class="btn btn-primary" href="{{route('admin.users.create')}}" >
                        Create new Admin
                    </a>
{{--                    <span class="example-toggle" data-toggle="tooltip" title="" data-original-title="View code"></span>--}}
{{--                    <span class="example-copy" data-toggle="tooltip" title="" data-original-title="Copy code"></span>--}}
                </div>
            </div>

        </div>
        <div class="card-body">

            @if(session()->has('success'))
                <div class="row">


                    <label class="alert alert-success">
                            {{session()->get('success')}}
                    </label>
                </div>
                @endif
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>name</th>
                    <th>email</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                <tr>
                    <td> {{$user->id}}</td>
                    <td> {{$user->name}}</td>
                    <td> {{$user->email}}</td>
                    <td> <a href="{{route('admin.users.edit',['admin'=>$user->id])}}" >
                            <i class="fa fa-pen"></i>
                        </a>
                    </td>

                    <td>




                        <form  action="{{ route('admin.users.destroy',$user->id) }} " method="POST"  class="delete-admin">
                            @csrf
                            <button class="btn btn-xs btn-danger" type="submit">
                                <i class="fa fa-trash"></i>
                            </button>
                        </form>
                    </td>

                </tr>
                @endforeach
                </tbody>
            </table>




        </div>
    </div>
@endsection